force-app/main/default/objects/Case/fields/Disposition_1__c.field-meta.xml
<CustomField>
    <fullName>Disposition_1__c</fullName>
    <label>Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>243/391 Both Warehouses Cancel Request *</fullName>
                <isActive>false</isActive>
                <label>243/391 Both Warehouses Cancel Request</label>
            </value>
            <value>
                <fullName>243 Assured</fullName>
                <isActive>false</isActive>
                <label>243 Assured</label>
            </value>
            <value>
                <fullName>243 Assured Cancel  *</fullName>
                <isActive>false</isActive>
                <label>243 Assured Cancel  *</label>
            </value>
            <value>
                <fullName>327 Drop Ship</fullName>
                <isActive>false</isActive>
                <label>327 Drop Ship</label>
            </value>
            <value>
                <fullName>327 DS Cancel Request</fullName>
                <isActive>false</isActive>
                <label>327 DS Cancel Request</label>
            </value>
            <value>
                <fullName>391 SFS Cancelled in StoreNet</fullName>
                <isActive>false</isActive>
                <label>391 SFS Cancelled in StoreNet</label>
            </value>
            <value>
                <fullName>391 SFS - Cancelled in StoreNet</fullName>
                <isActive>false</isActive>
                <label>391 SFS - Cancelled in StoreNet</label>
            </value>
            <value>
                <fullName>391 SFS Cancel Request *</fullName>
                <isActive>false</isActive>
                <label>391 SFS Cancel Request *</label>
            </value>
            <value>
                <fullName>391 SFS - Changed in StoreNet</fullName>
                <isActive>false</isActive>
                <label>391 SFS - Changed in StoreNet</label>
            </value>
            <value>
                <fullName>391 SFS - Unable to update StoreNet</fullName>
                <isActive>false</isActive>
                <label>391 SFS - Unable to update StoreNet</label>
            </value>
            <value>
                <fullName>396 ISPU Cancel request</fullName>
                <isActive>false</isActive>
                <label>396 ISPU Cancel request</label>
            </value>
            <value>
                <fullName>Accepted in error</fullName>
            </value>
            <value>
                <fullName>Accepted in error - SFS</fullName>
                <isActive>false</isActive>
                <label>Accepted in error - SFS</label>
            </value>
            <value>
                <fullName>Activation</fullName>
                <isActive>false</isActive>
                <label>Activation</label>
            </value>
            <value>
                <fullName>Add/Update/Remove from Email List</fullName>
            </value>
            <value>
                <fullName>Add/Update to Email Mailing List</fullName>
                <isActive>false</isActive>
                <label>Add/Update to Email Mailing List</label>
            </value>
            <value>
                <fullName>Address Correction</fullName>
            </value>
            <value>
                <fullName>Ad Misprint</fullName>
                <isActive>false</isActive>
                <label>Ad Misprint</label>
            </value>
            <value>
                <fullName>AL1</fullName>
                <isActive>false</isActive>
                <label>AL1</label>
            </value>
            <value>
                <fullName>AL1/SFS Both Warehouses Cancel Request *</fullName>
                <isActive>false</isActive>
                <label>AL1/SFS Both Warehouses Cancel Request *</label>
            </value>
            <value>
                <fullName>AL1 Cancel *</fullName>
                <isActive>false</isActive>
                <label>AL1 Cancel *</label>
            </value>
            <value>
                <fullName>Alleged Safety Concerns (no injury)</fullName>
                <isActive>false</isActive>
                <label>Alleged Safety Concerns (no injury)</label>
            </value>
            <value>
                <fullName>Allergic Reaction</fullName>
                <isActive>false</isActive>
                <label>Allergic Reaction</label>
            </value>
            <value>
                <fullName>Already Shipped</fullName>
                <isActive>false</isActive>
                <label>Already Shipped</label>
            </value>
            <value>
                <fullName>Anti Spam Law</fullName>
                <isActive>false</isActive>
                <label>Anti Spam Law</label>
            </value>
            <value>
                <fullName>Appeasement</fullName>
                <isActive>false</isActive>
                <label>Appeasement</label>
            </value>
            <value>
                <fullName>Authorization</fullName>
                <isActive>false</isActive>
                <label>Authorization</label>
            </value>
            <value>
                <fullName>Availability Inquiry Advertised Item</fullName>
                <color>#FF9966</color>
                <label>Availability Inquiry Advertised Item</label>
            </value>
            <value>
                <fullName>Availability Inquiry Non-Advertised</fullName>
            </value>
            <value>
                <fullName>Availability Inquiry Non-Advertised Item</fullName>
                <isActive>false</isActive>
                <label>Availability Inquiry Non-Advertised Item</label>
            </value>
            <value>
                <fullName>Chat terminated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The store in which this case should be routed to.</description>
    <inlineHelpText>The store in which this case should be routed to.</inlineHelpText>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>A TRU Store Location.</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Keytree_ID__c.field-meta.xml
<CustomField>
    <fullName>Keytree_ID__c</fullName>
    <description>Keytree&apos;s unique identifier for a Store Location.</description>
    <externalId>true</externalId>
    <label>Keytree ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CloseOrphanChatCasesBatch.cls
/*
    @Purpose        : Scheduled process for closing Open cases with chat origin and 
					  NOT having any Live Chat Transcripts associated with them
    @Created Date   : 29/10/2020
*/
public class CloseOrphanChatCasesBatch implements Database.Batchable<sObject>, schedulable {
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query;
        
        if(Test.isRunningTest()){
            query = 'SELECT Id, (SELECT Id FROM LiveChatTranscripts) FROM Case WHERE Origin = \'Chat\' AND Status = \'New\'';
        }
        else{
            query = 'SELECT Id, (SELECT Id FROM LiveChatTranscripts) FROM Case WHERE Owner.Name = \'Automated Process\' AND Origin = \'Chat\' AND Status = \'New\'';
        }
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Case> caseList) { 
        Store__c onlineStore;
        Id contactusRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Contact Us').getRecordTypeId(); 

        try{
            onlineStore = [SELECT Id FROM Store__c WHERE Keytree_ID__c = '3580' LIMIT 1];
        }
        catch(Exception e){
            System.debug('Exception in fetching online store: ' + e.getMessage());
        }
        
 
        for(Case caseRecord : caseList){   
            if(caseRecord.LiveChatTranscripts.isEmpty()){
                caseRecord.Status = 'Closed';
                caseRecord.Type = 'Unidentified';
                caseRecord.Subject = 'Unidentified';
                caseRecord.Disposition_1__c = 'Chat terminated';
                caseRecord.Description = 'Chat terminated';
                caseRecord.RecordTypeId = contactusRecordTypeId;
                
                if(onlineStore != null && onlineStore.Id != null){
                    caseRecord.Store__c = onlineStore.Id;
				}
            }
        }
                  
        Database.update(caseList);
    }   
    
    
    public void finish(Database.BatchableContext BC) {}
    
    public void execute(SchedulableContext SC) {
        Database.executebatch(new CloseOrphanChatCasesBatch());
    }
}