force-app/main/default/objects/Case/fields/Disposition_1__c.field-meta.xml
<CustomField>
    <fullName>Disposition_1__c</fullName>
    <label>Level 1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>243/391 Both Warehouses Cancel Request *</fullName>
                <isActive>false</isActive>
                <label>243/391 Both Warehouses Cancel Request</label>
            </value>
            <value>
                <fullName>243 Assured</fullName>
                <isActive>false</isActive>
                <label>243 Assured</label>
            </value>
            <value>
                <fullName>243 Assured Cancel  *</fullName>
                <isActive>false</isActive>
                <label>243 Assured Cancel  *</label>
            </value>
            <value>
                <fullName>327 Drop Ship</fullName>
                <isActive>false</isActive>
                <label>327 Drop Ship</label>
            </value>
            <value>
                <fullName>327 DS Cancel Request</fullName>
                <isActive>false</isActive>
                <label>327 DS Cancel Request</label>
            </value>
            <value>
                <fullName>391 SFS Cancelled in StoreNet</fullName>
                <isActive>false</isActive>
                <label>391 SFS Cancelled in StoreNet</label>
            </value>
            <value>
                <fullName>391 SFS - Cancelled in StoreNet</fullName>
                <isActive>false</isActive>
                <label>391 SFS - Cancelled in StoreNet</label>
            </value>
            <value>
                <fullName>391 SFS Cancel Request *</fullName>
                <isActive>false</isActive>
                <label>391 SFS Cancel Request *</label>
            </value>
            <value>
                <fullName>391 SFS - Changed in StoreNet</fullName>
                <isActive>false</isActive>
                <label>391 SFS - Changed in StoreNet</label>
            </value>
            <value>
                <fullName>391 SFS - Unable to update StoreNet</fullName>
                <isActive>false</isActive>
                <label>391 SFS - Unable to update StoreNet</label>
            </value>
            <value>
                <fullName>396 ISPU Cancel request</fullName>
                <isActive>false</isActive>
                <label>396 ISPU Cancel request</label>
            </value>
            <value>
                <fullName>Accepted in error</fullName>
            </value>
            <value>
                <fullName>Accepted in error - SFS</fullName>
                <isActive>false</isActive>
                <label>Accepted in error - SFS</label>
            </value>
            <value>
                <fullName>Activation</fullName>
                <isActive>false</isActive>
                <label>Activation</label>
            </value>
            <value>
                <fullName>Add/Update/Remove from Email List</fullName>
            </value>
            <value>
                <fullName>Add/Update to Email Mailing List</fullName>
                <isActive>false</isActive>
                <label>Add/Update to Email Mailing List</label>
            </value>
            <value>
                <fullName>Address Correction</fullName>
            </value>
            <value>
                <fullName>Ad Misprint</fullName>
                <isActive>false</isActive>
                <label>Ad Misprint</label>
            </value>
            <value>
                <fullName>AL1</fullName>
                <isActive>false</isActive>
                <label>AL1</label>
            </value>
            <value>
                <fullName>AL1/SFS Both Warehouses Cancel Request *</fullName>
                <isActive>false</isActive>
                <label>AL1/SFS Both Warehouses Cancel Request *</label>
            </value>
            <value>
                <fullName>AL1 Cancel *</fullName>
                <isActive>false</isActive>
                <label>AL1 Cancel *</label>
            </value>
            <value>
                <fullName>Alleged Safety Concerns (no injury)</fullName>
                <isActive>false</isActive>
                <label>Alleged Safety Concerns (no injury)</label>
            </value>
            <value>
                <fullName>Allergic Reaction</fullName>
                <isActive>false</isActive>
                <label>Allergic Reaction</label>
            </value>
            <value>
                <fullName>Already Shipped</fullName>
                <isActive>false</isActive>
                <label>Already Shipped</label>
            </value>
            <value>
                <fullName>Anti Spam Law</fullName>
                <isActive>false</isActive>
                <label>Anti Spam Law</label>
            </value>
            <value>
                <fullName>Appeasement</fullName>
                <isActive>false</isActive>
                <label>Appeasement</label>
            </value>
            <value>
                <fullName>Authorization</fullName>
                <isActive>false</isActive>
                <label>Authorization</label>
            </value>
            <value>
                <fullName>Availability Inquiry Advertised Item</fullName>
                <color>#FF9966</color>
                <label>Availability Inquiry Advertised Item</label>
            </value>
            <value>
                <fullName>Availability Inquiry Non-Advertised</fullName>
            </value>
            <value>
                <fullName>Availability Inquiry Non-Advertised Item</fullName>
                <isActive>false</isActive>
                <label>Availability Inquiry Non-Advertised Item</label>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
            <value>
                <fullName>In Store</fullName>
                <isActive>false</isActive>
                <label>In Store</label>
            </value>
            <value>
                <fullName>Test</fullName>
                <isActive>false</isActive>
                <label>Test</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/District_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Email__c</fullName>
    <label>Regional VP Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/KIT_Status__c.field-meta.xml
<CustomField>
    <fullName>KIT_Status__c</fullName>
    <label>KIT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting on Store</fullName>
            </value>
            <value>
                <fullName>Waiting on Support</fullName>
            </value>
            <value>
                <fullName>Waiting on Customer</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Store__c.field-meta.xml
<CustomField>
    <fullName>Store__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The store in which this case should be routed to.</description>
    <inlineHelpText>The store in which this case should be routed to.</inlineHelpText>
    <label>Store</label>
    <referenceTo>Store__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Store_ID__c.field-meta.xml
<CustomField>
    <fullName>Store_ID__c</fullName>
    <label>Store ID</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Store__c/Store__c.object-meta.xml
<CustomObject>
    <description>A TRU Store Location.</description>
    <label>Store</label>
    <nameField>
        <label>Store Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store__c/fields/Director_Email__c.field-meta.xml
<CustomField>
    <fullName>Director_Email__c</fullName>
    <label>Store Manager Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/District_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>District_Manager_Email__c</fullName>
    <label>Regional VP Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Store__c/fields/Keytree_ID__c.field-meta.xml
<CustomField>
    <fullName>Keytree_ID__c</fullName>
    <description>Keytree&apos;s unique identifier for a Store Location.</description>
    <externalId>true</externalId>
    <label>Keytree ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Store__c/fields/Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Manager_Email__c</fullName>
    <label>Manager Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandlerTest.cls
@isTest
public class CaseTriggerHandlerTest {
    static testmethod void caseCommentShouldBeGenerated(){
        Test.startTest();
        
        Store__c store = new Store__c();
        store.Manager_Email__c = 'test@test.com';
        store.Director_Email__c = 'test@test.com';
        store.District_Manager_Email__c = 'test@test.com';
        store.Keytree_ID__c = '123456';
        
        insert store;
        
        Case inStoreCaseWithStore = new Case();
        inStoreCaseWithStore.Reason = 'In Store';
        inStoreCaseWithStore.Store_ID__c = '123456';
        insert inStoreCaseWithStore;
        
        Case inStoreSaved = [SELECT Id, recordType.Name, Store__r.Id FROM Case WHERE ID = : inStoreCaseWithStore.Id];
        System.assertEquals(inStoreSaved.Store__r.Id, store.Id);
        System.assertEquals(inStoreSaved.recordType.Name, 'In Store Case');
        
        Case inStoreCaseWithOutStore = new Case();
        inStoreCaseWithOutStore.Reason = 'In Store';
        insert inStoreCaseWithOutStore;
                
        Case inStoreWOStoreSaved = [SELECT Id, recordType.Name, KIT_Status__c FROM Case WHERE ID = : inStoreCaseWithOutStore.Id];
        System.assertEquals(inStoreWOStoreSaved.KIT_Status__c, 'Waiting on Support');
        
        Case priceMatchCase = new Case();
        priceMatchCase.Reason = 'Price Adjustment';
        insert priceMatchCase;
        
        Case priceMatchSaved = [SELECT Id, recordType.Name FROM Case WHERE ID = : priceMatchCase.Id];
        System.assertEquals(priceMatchSaved.recordType.Name, 'Price Adjustment');
        
        
        Case contactUsCase = new Case();
        contactUsCase.Reason = 'Promotion General';
        insert contactUsCase;
        
        Case contactUsSaved = [SELECT Id, recordType.Name FROM Case WHERE ID = : contactUsCase.Id];
        System.assertEquals(contactUsSaved.recordType.Name, 'Contact Us');
        
        Test.stopTest();
        
        Case contactUsFRCase = new Case();
        contactUsFRCase.Reason = 'Ramassage de commande';
        insert contactUsFRCase;
        
        Case instoreFRCase = new Case();
        instoreFRCase.Reason = 'En Magasin';
        insert instoreFRCase;
        
        Case pricematchFRCase = new Case();
        pricematchFRCase.Reason = 'Ajustement de prix';
        insert pricematchFRCase;
        
        Account account = new Account(LastName = 'Test');
        insert account;
        
        contactUsSaved.AccountId = account.Id;
        contactUsSaved.Status = 'Closed';
        update contactUsSaved;
        
        contactUsSaved.Status = 'Pending';
        update contactUsSaved;
        
        contactUsSaved.Type = 'Payment';
        contactUsSaved.Disposition_1__c = 'Follow Up';
        update contactUsSaved;
        
        Case emailCase= new Case();
        emailCase.Origin= 'email';
        emailCase.SuppliedEmail= 'test@a.com';
        emailCase.SuppliedName ='Case Email';
        emailCase.SuppliedPhone = '76763536383';
        insert emailCase;
   }

}