force-app/main/default/objects/Appeasement__c/Appeasement__c.object-meta.xml
<CustomObject>
    <label>Appeasement</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Appeasement ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appeasement</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appeasement__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Appeasements</relationshipLabel>
    <relationshipName>Appeasements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeasement__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Appeasements</relationshipLabel>
    <relationshipName>Appeasements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Appeasement__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose_of_Appeasement__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checklist - 8 mth - Online</fullName>
            </value>
            <value>
                <fullName>Completion - 9 mth - Online</fullName>
            </value>
            <value>
                <fullName>Completion - 9 mth - Stores</fullName>
            </value>
            <value>
                <fullName>Congrats - 1 mth post - Online</fullName>
            </value>
            <value>
                <fullName>Congrats - 1 mth post - Stores</fullName>
            </value>
            <value>
                <fullName>Family And Friends - 7mth - Online</fullName>
            </value>
            <value>
                <fullName>Family And Friends - 7mth - Stores</fullName>
            </value>
            <value>
                <fullName>Feeding Infant - 2 mth post - Online</fullName>
            </value>
            <value>
                <fullName>Feeding Infant - 2 mth post - Stores</fullName>
            </value>
            <value>
                <fullName>FisherPrice - 6mth - Online</fullName>
            </value>
            <value>
                <fullName>FisherPrice - 6mth - Stores</fullName>
            </value>
            <value>
                <fullName>Welcome - Online</fullName>
            </value>
            <value>
                <fullName>Welcome - Stores</fullName>
            </value>
            <value>
                <fullName>$5</fullName>
            </value>
            <value>
                <fullName>$10</fullName>
            </value>
            <value>
                <fullName>$15</fullName>
            </value>
            <value>
                <fullName>$20</fullName>
            </value>
            <value>
                <fullName>$25</fullName>
            </value>
            <value>
                <fullName>$30</fullName>
            </value>
            <value>
                <fullName>$35</fullName>
            </value>
            <value>
                <fullName>$40</fullName>
            </value>
            <value>
                <fullName>$45</fullName>
            </value>
            <value>
                <fullName>$50</fullName>
            </value>
            <value>
                <fullName>10%</fullName>
            </value>
            <value>
                <fullName>15%</fullName>
            </value>
            <value>
                <fullName>20%</fullName>
            </value>
            <value>
                <fullName>25%</fullName>
            </value>
            <value>
                <fullName>30%</fullName>
            </value>
            <value>
                <fullName>40%</fullName>
            </value>
            <value>
                <fullName>50%</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appeasement__c/fields/Purpose_of_Appeasement__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_Appeasement__c</fullName>
    <label>Purpose of Appeasement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Baby Registry</fullName>
            </value>
            <value>
                <fullName>Bulk Order</fullName>
            </value>
            <value>
                <fullName>CS Appeasement</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>ECR</fullName>
            </value>
            <value>
                <fullName>Misship</fullName>
            </value>
            <value>
                <fullName>Order Replacement</fullName>
            </value>
            <value>
                <fullName>RClub</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Shortship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appeasement_Code__c/Appeasement_Code__c.object-meta.xml
<CustomObject>
    <label>Appeasement Code</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Appeasement Code ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appeasement Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Appeasement_Code__c/fields/Discount_Type__c.field-meta.xml
<CustomField>
    <fullName>Discount_Type__c</fullName>
    <label>Discount Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Purpose_of_Appeasement__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checklist - 8 mth - Online</fullName>
            </value>
            <value>
                <fullName>Completion - 9 mth - Online</fullName>
            </value>
            <value>
                <fullName>Completion - 9 mth - Stores</fullName>
            </value>
            <value>
                <fullName>Congrats - 1 mth post - Online</fullName>
            </value>
            <value>
                <fullName>Congrats - 1 mth post - Stores</fullName>
            </value>
            <value>
                <fullName>Family And Friends - 7mth - Online</fullName>
            </value>
            <value>
                <fullName>Family And Friends - 7mth - Stores</fullName>
            </value>
            <value>
                <fullName>Feeding Infant - 2 mth post - Online</fullName>
            </value>
            <value>
                <fullName>Feeding Infant - 2 mth post - Stores</fullName>
            </value>
            <value>
                <fullName>Welcome - Online</fullName>
            </value>
            <value>
                <fullName>Welcome - Stores</fullName>
            </value>
            <value>
                <fullName>$10</fullName>
            </value>
            <value>
                <fullName>$15</fullName>
            </value>
            <value>
                <fullName>$20</fullName>
            </value>
            <value>
                <fullName>$25</fullName>
            </value>
            <value>
                <fullName>$30</fullName>
            </value>
            <value>
                <fullName>$35</fullName>
            </value>
            <value>
                <fullName>$40</fullName>
            </value>
            <value>
                <fullName>$45</fullName>
            </value>
            <value>
                <fullName>$50</fullName>
            </value>
            <value>
                <fullName>10%</fullName>
            </value>
            <value>
                <fullName>15%</fullName>
            </value>
            <value>
                <fullName>20%</fullName>
            </value>
            <value>
                <fullName>25%</fullName>
            </value>
            <value>
                <fullName>30%</fullName>
            </value>
            <value>
                <fullName>40%</fullName>
            </value>
            <value>
                <fullName>50%</fullName>
            </value>
            <value>
                <fullName>$150</fullName>
            </value>
            <value>
                <fullName>$300</fullName>
            </value>
            <value>
                <fullName>$600</fullName>
            </value>
            <value>
                <fullName>Baby Registry</fullName>
                <isActive>false</isActive>
                <label>Baby Registry</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appeasement_Code__c/fields/Purpose_of_Appeasement__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_Appeasement__c</fullName>
    <label>Purpose of Appeasement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Baby Registry</fullName>
            </value>
            <value>
                <fullName>Birthday - Stores</fullName>
                <isActive>false</isActive>
                <label>Birthday - Stores</label>
            </value>
            <value>
                <fullName>Bulk Order</fullName>
            </value>
            <value>
                <fullName>Checklist - 8 mth - Online</fullName>
                <isActive>false</isActive>
                <label>Checklist - 8 mth - Online</label>
            </value>
            <value>
                <fullName>Checklist - 8 mth - Stores</fullName>
                <isActive>false</isActive>
                <label>Checklist - 8 mth - Stores</label>
            </value>
            <value>
                <fullName>Completion - 9 mth - Online</fullName>
                <isActive>false</isActive>
                <label>Completion - 9 mth - Online</label>
            </value>
            <value>
                <fullName>Completion - 9 mth - Stores</fullName>
                <isActive>false</isActive>
                <label>Completion - 9 mth - Stores</label>
            </value>
            <value>
                <fullName>Congrats - 1 mth post - Online</fullName>
                <isActive>false</isActive>
                <label>Congrats - 1 mth post - Online</label>
            </value>
            <value>
                <fullName>Congrats - 1 mth post - Stores</fullName>
                <isActive>false</isActive>
                <label>Congrats - 1 mth post - Stores</label>
            </value>
            <value>
                <fullName>CS Appeasement</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>ECR</fullName>
            </value>
            <value>
                <fullName>Family And Friends - 7mth - Online</fullName>
                <isActive>false</isActive>
                <label>Family And Friends - 7mth - Online</label>
            </value>
            <value>
                <fullName>Family And Friends - 7mth - Stores</fullName>
                <isActive>false</isActive>
                <label>Family And Friends - 7mth - Stores</label>
            </value>
            <value>
                <fullName>Feeding Infant - 2 mth post - Online</fullName>
                <isActive>false</isActive>
                <label>Feeding Infant - 2 mth post - Online</label>
            </value>
            <value>
                <fullName>Feeding Infant - 2 mth post - Stores</fullName>
                <isActive>false</isActive>
                <label>Feeding Infant - 2 mth post - Stores</label>
            </value>
            <value>
                <fullName>Misship</fullName>
            </value>
            <value>
                <fullName>Order Replacement</fullName>
            </value>
            <value>
                <fullName>RClub</fullName>
            </value>
            <value>
                <fullName>Registry completion - Online</fullName>
                <isActive>false</isActive>
                <label>Registry completion - Online</label>
            </value>
            <value>
                <fullName>Registry completion - Stores</fullName>
                <isActive>false</isActive>
                <label>Registry completion - Stores</label>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
            <value>
                <fullName>Shortship</fullName>
            </value>
            <value>
                <fullName>Welcome - Online</fullName>
                <isActive>false</isActive>
                <label>Welcome - Online</label>
            </value>
            <value>
                <fullName>Welcome - Stores</fullName>
                <isActive>false</isActive>
                <label>Welcome - Stores</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Appeasement_Code__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AppeasementCodeControllerTest.cls
/*
    @Purpose        : Test class for AppeasementCodeController
    @Created Date   : 18/08/2020
*/ 
@isTest
public class AppeasementCodeControllerTest { 
    
    @TestSetup
    public static void checkAppeasement(){
        Contact newContact = new Contact();
        newContact.LastName = 'test';
        newContact.Email = 'test@abc.com';
        insert newContact;
       
        Case newcase = new Case();
        newcase.Type = 'Account';
        newcase.Status = 'New';
        newcase.ContactId = newContact.Id;
        insert newcase;
         
        Appeasement__c appeasement = new Appeasement__c();
        appeasement.Purpose_of_Appeasement__c = 'Baby Registry';
        appeasement.Case__c = newcase.Id;
        appeasement.Contact__c = newContact.id;
        appeasement.Discount_Type__c = 'Checklist - 8 mth - Online';
        insert appeasement;  
        
        Appeasement_Code__c appeasementCode = new Appeasement_Code__c();
        appeasementCode.Status__c = 'Available';
        appeasementCode.Discount_Type__c = appeasement.Discount_Type__c;
        appeasementCode.Purpose_of_Appeasement__c = appeasement.Purpose_of_Appeasement__c;
        insert appeasementCode;
     
    }
    
    @isTest
    static void test(){
        Test.startTest();
        Appeasement__c appeasement = [SELECT Purpose_of_Appeasement__c, Discount_Type__c 
                                      FROM Appeasement__c WHERE Purpose_of_Appeasement__c = 'Baby Registry' limit 1];
        
        String response = AppeasementCodeController.getAvailableAppeasementCode(appeasement.Id); 
        
        Test.stopTest();
        
        System.assert(response.contains('Success!'));
        
        response = AppeasementCodeController.getAvailableAppeasementCode(null);
        
        System.assert(response == 'Error! Failed to get the Appeasement Code.');
    }
}