force-app/main/default/objects/Account/fields/Baby_Baby_Items__c.field-meta.xml
<CustomField>
    <fullName>Baby_Baby_Items__c</fullName>
    <label>Baby &amp; Baby Items</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baby</fullName>
            </value>
            <value>
                <fullName>Baby Gear &amp; Essentials</fullName>
            </value>
            <value>
                <fullName>Nursury &amp; Feeding</fullName>
            </value>
            <value>
                <fullName>Pregnancy &amp; Parenting</fullName>
            </value>
            <value>
                <fullName>Safety, Health &amp; Wellness</fullName>
            </value>
            <value>
                <fullName>Toys &amp; Activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_BRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_BRU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether an account has opted in to Babies R Us weekly marketing emails.  Initially loaded from YM, then linked to preference center.</description>
    <label>Baby</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_TRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_TRU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether an account has opted in to Toys R Us weekly marketing emails.  Initially loaded from YM, then linked to preference center.</description>
    <label>Toys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
                <default>true</default>
                <label>EN</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Toys_Toys_Items__c.field-meta.xml
<CustomField>
    <fullName>Toys_Toys_Items__c</fullName>
    <label>Toys &amp; Toys Items</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Toys</fullName>
            </value>
            <value>
                <fullName>Active Play &amp; Outdoor</fullName>
            </value>
            <value>
                <fullName>Books</fullName>
            </value>
            <value>
                <fullName>Collectors - Grownups</fullName>
            </value>
            <value>
                <fullName>Collectors - Kids</fullName>
            </value>
            <value>
                <fullName>Education &amp; Learning Toys Games</fullName>
            </value>
            <value>
                <fullName>Preschool Playtime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubscriptionCenterPageControllerTest.cls
@isTest
public class SubscriptionCenterPageControllerTest {
    
    public static testmethod void SubscriptionCenterPageControllerTest(){
        
        Account accountRec = new Account();
        //accountRec.IsPersonAccount = true;
        accountRec.FirstName = 'Test';
        accountRec.LastName = 'Test';
        accountRec.Language_Preference__c = 'EN';
        accountRec.Email_Opt_In_TRU__c = true;
        accountRec.Email_Opt_In_BRU__c = true;
        accountRec.PersonHasOptedOutOfEmail = true;
        accountRec.Toys_Toys_Items__c = 'Active Play & Outdoor;Books;Collectors - Grownups;Collectors - Kids;Education & Learning Toys Games;Preschool Playtime';
        accountRec.Baby_Baby_Items__c ='Baby Gear & Essentials;Nursury & Feeding;Pregnancy & Parenting;Safety, Health & Wellness;Toys & Activities';    
       
 
            
        Insert accountRec;
        
        Test.setCurrentPageReference(new PageReference('Page.SubscriptionCenterPage')); 
        System.currentPageReference().getParameters().put('id', accountRec.Id);
        System.currentPageReference().getParameters().put('unsub', 'true');
        
        SubscriptionCenterPageController testAccPlan = new SubscriptionCenterPageController();
       // testAccPlan.updateAccount();
               testAccPlan.toys = true;
               testAccPlan.activePlayOutdoor = true;
               testAccPlan.books = true;
               testAccPlan.collectorsGrownups = true;
               testAccPlan.collectorsKids = true;
               testAccPlan.educationLearningToysGames = true;
               testAccPlan.preschoolPlaytime = true;
               testAccPlan.baby = true;
               testAccPlan.babyGearEssentials = true;
			   testAccPlan.nurseryFeeding = true;          
               testAccPlan.pregnancyParenting = true;
               testAccPlan.safetyHealthWellness = true;
               testAccPlan.toysActivities = true;
               testAccPlan.clothing = true;
               testAccPlan.eventsAndActivities = true;
               testAccPlan.partyAndGiftGiving = true;
                   
                   
                   
        testAccPlan.updateOut();
        testAccPlan.accountunsub();
        testAccPlan.accountUpdate();
        testAccPlan.changeLanguage();
    }
    
    
}