force-app/main/default/objects/Account/fields/Children_Count__c.field-meta.xml
<CustomField>
    <fullName>Children_Count__c</fullName>
    <label>Children Count</label>
    <summaryForeignKey>Child__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Child Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Child__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>Birthday</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Child__c/fields/Duplicate_Group__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Group__c</fullName>
    <formula>Name__c &amp; &quot; &quot; &amp; TEXT(Birthday__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Duplicate Group</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Child__c/fields/Duplicate_Record__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Duplicate Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Child__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DuplicateAccountBatch.cls
public class DuplicateAccountBatch implements Database.Batchable<Sobject>{ 
    
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'Select Id From Account Where Children_Count__c != 0 ';// AND Id IN : acclist LIMIT '+limistr; 
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Sobject> scope){
        try{ 
            for(sObject sobj : scope){
                Map<string, List<Child__c>> dupChilds = new Map<string, List<Child__c>>();
            	Map<account,List<string>> accUniqyuechildrens = new Map<account,List<string>>(); 
                List<String> csvRowValues = new List<String>();
                Account acc = (Account)sobj;
                List<Child__c> childRecordsToUpdate = new List<Child__c>();
                List<Child__c> childRecords = [SELECT Id, Duplicate_Record__c, Name, Account__c, Account__r.FirstName,Name__c, Account__r.LastName,  
                                               Birthday__c, Duplicate_Group__c, CreatedDate 
                                               FROM Child__c 
                                               WHERE Account__c =: acc.Id
                                               ORDER By Duplicate_Group__c];
                accUniqyuechildrens.put(acc, new List<string>());
                for(Child__c child : childRecords){
                    
                    if(dupChilds.containsKey(child.Duplicate_Group__c)){
                        child.Duplicate_Record__c = true;
                        childRecordsToUpdate.add(child);
                        dupChilds.get(child.Duplicate_Group__c).add(child);
                    }else{
                        dupChilds.put(child.Duplicate_Group__c, new List<Child__c>{child});
                        accUniqyuechildrens.get(acc).add(child.Duplicate_Group__c);
                    }
                } 
                
                for(String val : accUniqyuechildrens.get(acc)){
                    if(dupChilds.get(val).size() > 1){
                        for(Child__c child : dupChilds.get(val)){
                            string accId = child.Account__c;
                            string accName =  child.Account__r.FirstName + ' ' + child.Account__r.LastName;
                            string childName = child.Name__c;
                            string Birthdate = string.valueOf(child.Birthday__c);
                            string createdDate = child.CreatedDate.format('M/d/yyyy h:mm:ss a z'); 
                            
                            String rowStr = accId + ',' + accName + ',' + child.Duplicate_Group__c + ',' + child.Id + ',' + child.Name__c + ',' + Birthdate + ','+ createdDate ;
                            csvRowValues.add(rowStr);
                        }
                    } 
                } 
                
                /*String documentName = Label.Document_Name; 
                List<Document> doclist  = [SELECT Id, Name, DeveloperName, Body FROM Document Where Name =: documentName];
                
                if(doclist != null && !doclist.isEmpty()){
                    document doc = doclist[0];
                    string strbody = doc.Body.toString();
                    strbody = strbody + '\n' + String.join(csvRowValues,'\n');
                    doc.Body = Blob.valueOf(strbody);
                    update doc;
                }*/
                
                update childRecordsToUpdate;
            } 
            
        }catch(Exception e){
            system.debug('Exception Occured ==== '+ e);
        } 
        
    }
    
    public void finish(Database.BatchableContext BC){ 
    }
    
}