force-app/main/default/objects/Account/fields/Child_Birthday_Email_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Child_Birthday_Email_Opt_In_Date__c</fullName>
    <label>Child Birthday Email Opt In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Child_Birthday_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Child_Birthday_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Child Birthday Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_BRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_BRU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether an account has opted in to Babies R Us weekly marketing emails.  Initially loaded from YM, then linked to preference center.</description>
    <label>Baby</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_Date_BRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_Date_BRU__c</fullName>
    <description>The date the Account opted in to BRU weekly marketing emails.</description>
    <label>Email Opt In Date BRU</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_Date_TRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_Date_TRU__c</fullName>
    <description>The date the account opted in to TRU weekly marketing emails.</description>
    <label>Email Opt In Date TRU</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_TRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_TRU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether an account has opted in to Toys R Us weekly marketing emails.  Initially loaded from YM, then linked to preference center.</description>
    <label>Toys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
                <default>true</default>
                <label>EN</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loyalty Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In_Date__c</fullName>
    <label>Loyalty Opt In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <description>Rewards number issued by Toys R Us.</description>
    <label>R-Club Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/R_Club_Number__c.object-meta.xml
<CustomObject>
    <label>R Club Number</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>SFSC System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>R Club Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/R_Club_Number__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>R Club Numbers</relationshipLabel>
    <relationshipName>R_Club_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/Loyalty_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loyalty Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/Loyalty_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In_Date__c</fullName>
    <label>Loyalty Opt In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <externalId>true</externalId>
    <label>R Club Number</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rclub_Number_Settings__c/Rclub_Number_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>R-club Number Settings</label>
</CustomObject>

force-app/main/default/objects/Rclub_Number_Settings__c/fields/IIN__c.field-meta.xml
<CustomField>
    <fullName>IIN__c</fullName>
    <label>IIN</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rclub_Number_Settings__c/fields/Online_English__c.field-meta.xml
<CustomField>
    <fullName>Online_English__c</fullName>
    <label>Online English</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rclub_Number_Settings__c/fields/Online_French__c.field-meta.xml
<CustomField>
    <fullName>Online_French__c</fullName>
    <label>Online French</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TRU_Opt_In_Dates_Mapping__c/TRU_Opt_In_Dates_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Mapping for populating Opt In Dates when parent field is filled.</description>
    <label>TRU Opt In Dates Mapping</label>
</CustomObject>

force-app/main/default/objects/TRU_Opt_In_Dates_Mapping__c/fields/Opt_In_Date_field__c.field-meta.xml
<CustomField>
    <fullName>Opt_In_Date_field__c</fullName>
    <label>Opt In Date field</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TRU_Subscriber_Config__c/TRU_Subscriber_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>TRU Subscriber Config</label>
</CustomObject>

force-app/main/default/objects/TRU_Subscriber_Config__c/fields/Default_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Default_Last_Name__c</fullName>
    <description>Default value for Last Name field for new Person Account (in case if new customer did not provide last name in registration form)</description>
    <label>Default Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TRUTestDataFactory.cls
/**
 * Created by i.yefremov on 25.07.2019.
 */

@isTest
public class  TRUTestDataFactory {

    public static void createTruSubscriberCustomSetting(){
        TRU_Subscriber_Config__c configRecord = new TRU_Subscriber_Config__c();
        configRecord.Default_Last_Name__c = 'Customer';
        insert configRecord;
    }

    public static List<Account> createAndInsertAccounts(Integer length, String language){
        List<Account> accList = createAccounts(length, language);

        insert accList;

        return accList;
    }

    public static List<Account> createAccounts(Integer length, String language){
        List<Account> accList = new List<Account>();
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();

        for (Integer i = 0; i < length; ++i){
            accList.add(new Account(
                    LastName = 'Test Account ' + (i + 1),
                    PersonEmail = 'testemail' + (i + 1) + '@test.mail',
                    Language_Preference__c = language,
                    RecordTypeId = rtId
            ));
        }

        return accList;
    }

    public static List<R_Club_Number__c> createRClubNumbers(Integer length, Id accountId){
        List<R_Club_Number__c> rClubNumberList = new List<R_Club_Number__c>();

        for (Integer i = 0; i < length; ++i){
            String rClubNumber = String.valueOf(length).leftPad(13, '0');

            rClubNumberList.add(new R_Club_Number__c(
                    R_Club_Number__c = rClubNumber,
                    Account__c = accountId
            ));
        }

        return rClubNumberList;
    }

    public static void createRclubNumberSettingsCustomSetting(){
        Rclub_Number_Settings__c setting = Rclub_Number_Settings__c.getOrgDefaults();
        setting.Number__c = 9;
        setting.Online_English__c = 3.0;
        setting.Online_French__c = 4.0;
        setting.IIN__c = 6666;
        insert setting;
    }


    public static void createOptInDatesMappingCustomSetting(){
        List<TRU_Opt_In_Dates_Mapping__c> setting = new List<TRU_Opt_In_Dates_Mapping__c>();
        setting.add(new TRU_Opt_In_Dates_Mapping__c(Name = 'Email_Opt_In_BRU__c', Opt_In_Date_field__c = 'Email_Opt_In_Date_BRU__c'));
        setting.add(new TRU_Opt_In_Dates_Mapping__c(Name = 'Email_Opt_In_TRU__c', Opt_In_Date_field__c = 'Email_Opt_In_Date_TRU__c'));
        setting.add(new TRU_Opt_In_Dates_Mapping__c(Name = 'Loyalty_Opt_In__c', Opt_In_Date_field__c = 'Loyalty_Opt_In_Date__c'));
        setting.add(new TRU_Opt_In_Dates_Mapping__c(Name = 'Child_Birthday_Opt_In__c', Opt_In_Date_field__c = 'Child_Birthday_Email_Opt_In_Date__c'));
        insert setting;
    }
}