force-app/main/default/objects/Account/fields/Child_Birthday_Email_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Child_Birthday_Email_Opt_In_Date__c</fullName>
    <label>Child Birthday Email Opt In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Child_Birthday_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Child_Birthday_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Child Birthday Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_BRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_BRU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether an account has opted in to Babies R Us weekly marketing emails.  Initially loaded from YM, then linked to preference center.</description>
    <label>Baby</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_Date_BRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_Date_BRU__c</fullName>
    <description>The date the Account opted in to BRU weekly marketing emails.</description>
    <label>Email Opt In Date BRU</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_Date_RLE__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_Date_RLE__c</fullName>
    <label>Email Opt In Date RLE</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_Date_TRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_Date_TRU__c</fullName>
    <description>The date the account opted in to TRU weekly marketing emails.</description>
    <label>Email Opt In Date TRU</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_RLE__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_RLE__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Clothing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_Opt_In_TRU__c.field-meta.xml
<CustomField>
    <fullName>Email_Opt_In_TRU__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Denotes whether an account has opted in to Toys R Us weekly marketing emails.  Initially loaded from YM, then linked to preference center.</description>
    <label>Toys</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loyalty Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In_Date__c</fullName>
    <label>Loyalty Opt In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registry__c/Registry__c.object-meta.xml
<CustomObject>
    <label>Registry</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Registry System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registries</relationshipLabel>
    <relationshipName>Registries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registry__c/fields/Account_Email_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>Account_Email_Opt_Out__c</fullName>
    <formula>Account__r.PersonHasOptedOutOfEmail</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Email Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Registry__c/fields/Inactive_Flag__c.field-meta.xml
<CustomField>
    <fullName>Inactive_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inactive Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandlerForOptIn.cls
/*
* @Purpose- Handler used from trigger to Update the Opt In Dates base on its respective Opt In checkBoxes
*/
public class AccountTriggerHandlerForOptIn {
    /*
* @Purpose - Method invoke on After update.
*/
    public static void SetOptInDates(Map<Id, Account> newAccountMap, Map<Id, Account> oldAccountMap) {
        try{
            List<Account> toUpdateAccountList = new List<Account>();
            System.debug('newAccountMap '+ newAccountMap);
            for(String accRecId : newAccountMap.keySet()) {
                Account oldAcc = oldAccountMap.get(accRecId);
                Account newAcc = newAccountMap.get(accRecId);
                
                if(newAcc.Email_Opt_In_BRU__c && oldAcc.Email_Opt_In_BRU__c != newAcc.Email_Opt_In_BRU__c){
                    newAcc.Email_Opt_In_Date_BRU__c = System.today();
                }else if(oldAcc.Email_Opt_In_BRU__c != newAcc.Email_Opt_In_BRU__c && !newAcc.Email_Opt_In_BRU__c){
                    //  newAcc.Email_Opt_In_Date_BRU__c = NULL;
                }
                
                if(newAcc.Child_Birthday_Opt_In__c && oldAcc.Child_Birthday_Opt_In__c != newAcc.Child_Birthday_Opt_In__c){
                    newAcc.Child_Birthday_Email_Opt_In_Date__c = System.today();
                }else if(oldAcc.Child_Birthday_Opt_In__c != newAcc.Child_Birthday_Opt_In__c && !newAcc.Child_Birthday_Opt_In__c){
                    // newAcc.Child_Birthday_Email_Opt_In_Date__c = NULL;
                }
                
                if(newAcc.Email_Opt_In_TRU__c && oldAcc.Email_Opt_In_TRU__c != newAcc.Email_Opt_In_TRU__c){
                    newAcc.Email_Opt_In_Date_TRU__c = System.today();
                }else if(oldAcc.Email_Opt_In_TRU__c != newAcc.Email_Opt_In_TRU__c && !newAcc.Email_Opt_In_TRU__c){
                    // newAcc.Email_Opt_In_Date_TRU__c = NULL;
                }
                
                //LastModifedDate - 26-02-2021
                if(newAcc.Email_Opt_In_RLE__c && oldAcc.Email_Opt_In_RLE__c != newAcc.Email_Opt_In_RLE__c){
                    newAcc.Email_Opt_In_Date_RLE__c = System.today();
                }else if(oldAcc.Email_Opt_In_TRU__c != newAcc.Email_Opt_In_TRU__c && !newAcc.Email_Opt_In_TRU__c){
                    // newAcc.Email_Opt_In_Date_TRU__c = NULL;
                }
                
                if(oldAcc.Loyalty_Opt_In__c != newAcc.Loyalty_Opt_In__c && newAcc.Loyalty_Opt_In__c){
                    newAcc.Loyalty_Opt_In_Date__c = System.today();
                }       
            }}
        catch(exception e){
            system.debug('AccoungTRH :> '+json.serialize(e));
        }
    }
    
    /*
* @Purpose - Method invoke on After insert.
*/
    public static void SetOptInDates(List<Account> newAccountList) {
        try{
            List<Account> toUpdateAccountList = new List<Account>();
            System.debug('newAccountMap '+ newAccountList);
            for(Account newAcc : newAccountList) {
                
                if(newAcc.Email_Opt_In_BRU__c){
                    newAcc.Email_Opt_In_Date_BRU__c = System.today();
                }
                if(newAcc.Child_Birthday_Opt_In__c){
                    newAcc.Child_Birthday_Email_Opt_In_Date__c = System.today();
                }
                
                if(newAcc.Email_Opt_In_TRU__c){
                    newAcc.Email_Opt_In_Date_TRU__c = System.today();
                }
                
                //LastModifedDate - 26-02-2021
                if(newAcc.Email_Opt_In_RLE__c){
                    newAcc.Email_Opt_In_Date_RLE__c = System.today();
                }
                
                /*if(newAcc.Loyalty_Opt_In__c){
newAcc.Loyalty_Opt_In_Date__c = System.today();
} */   
            }
        }
        catch(exception e){
            system.debug('AccoungTRH :> '+json.serialize(e));
        }
    }
    
    public static void registryInactiveFlagUpdate(Map<Id, Account> newAccountMap){
        if(newAccountMap != null){
            if(!newAccountMap.isEmpty()){
                try{
                    List<Registry__c> listregistry = [Select Id, Name, Account__c, Inactive_Flag__c, Account_Email_Opt_Out__c, Account__r.PersonHasOptedOutOfEmail
                                                      FROM Registry__c
                                                      Where Account__c IN : newAccountMap.keyset() AND Account__r.PersonHasOptedOutOfEmail = true];
                    
                    if(listregistry != null){
                        for(Registry__c registry : listregistry){
                            registry.Inactive_Flag__c = true;
                        }
                        
                        update listregistry;
                    }
                    
                }
                catch(Exception e){
                    
                }
            }
        }
    }
}