force-app/main/default/objects/Account/fields/IsUpdate__c.field-meta.xml
<CustomField>
    <fullName>IsUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Order_SCCSync_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_SCCSync_Status__c</fullName>
    <description>This field holds Order Synchronised status with Salesforce Commerce Cloud.</description>
    <inlineHelpText>This field holds Order Synchronised status with Salesforce Commerce Cloud.</inlineHelpText>
    <label>Order SCC Sync Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
            </value>
            <value>
                <fullName>Updated</fullName>
            </value>
            <value>
                <fullName>Synchronised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SFCC_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>SFCC_Order_Number__c</fullName>
    <description>This field holds Salesforce Commerce Cloud Order Number.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field holds Salesforce Commerce Cloud Order Number.</inlineHelpText>
    <label>OMS Order Number</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order/fields/SFCC_Order_Total__c.field-meta.xml
<CustomField>
    <fullName>SFCC_Order_Total__c</fullName>
    <description>This field holds Salesforce Commerce Cloud Order total value.</description>
    <inlineHelpText>This field holds Salesforce Commerce Cloud Order total value.</inlineHelpText>
    <label>Order Total</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OrderExtractBatchTest.cls
@isTest
public class OrderExtractBatchTest { 
    
    @testSetup
    private static void createData(){ 
        Document document;
        document = new Document();
        document.Body = Blob.valueOf('Some Text');
        document.ContentType = 'text/csv';
        document.DeveloperName = 'Order_Extract2';
        document.IsPublic = true;
        document.Name = 'Order Extract';
        document.FolderId = [select id from folder where name = 'Shared Documents'].id;
        insert document;
        
        Account account = new Account();
        account.Salutation ='Mr.';
        account.FirstName ='Test FirstName';
        account.MiddleName ='Test MidleName';
        account.LastName ='Test LastName';
        account.IsUpdate__c = false;
        
        INSERT account;
        List<Order> orderList = new List<Order>();
        
        for(Integer count = 0; count < 1001; count++){
            Order order = new Order();
            order.AccountId = account.Id;
            order.EffectiveDate = Date.today();
            order.Status = 'New';
            order.Order_SCCSync_Status__c = 'Created';
            order.SFCC_Order_Number__c = '08903428802193029' + count;
            order.SFCC_Order_Total__c = 1234;
            orderList.add(order);
        } 
        
        INSERT orderList;    
    }  
    
    @isTest
    private static void accountTest(){
        Test.startTest(); 
        
        OrderExtractBatch obj = new OrderExtractBatch();
        DataBase.executeBatch(obj); 
        
        Test.stopTest();
    }
    
}