force-app/main/default/objects/Account/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <label>Language Preference</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EN</fullName>
                <default>true</default>
                <label>EN</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/R_Club_Join_Date__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Join_Date__c</fullName>
    <description>This signifies the date that a customer joined the R-Club rewards program.</description>
    <label>R-Club Join Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <description>Rewards number issued by Toys R Us.</description>
    <label>R-Club Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/R_Club_Number__c.object-meta.xml
<CustomObject>
    <label>R Club Number</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>SFSC System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>R Club Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Join_Date__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Join_Date__c</fullName>
    <label>R Club Join Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <externalId>true</externalId>
    <label>R Club Number</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Rclub_Number_Settings__c/Rclub_Number_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>R-club Number Settings</label>
</CustomObject>

force-app/main/default/objects/Rclub_Number_Settings__c/fields/IIN__c.field-meta.xml
<CustomField>
    <fullName>IIN__c</fullName>
    <label>IIN</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rclub_Number_Settings__c/fields/Online_English__c.field-meta.xml
<CustomField>
    <fullName>Online_English__c</fullName>
    <label>Online English</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rclub_Number_Settings__c/fields/Online_French__c.field-meta.xml
<CustomField>
    <fullName>Online_French__c</fullName>
    <label>Online French</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AccountCardNumberHelper.cls
public with sharing class AccountCardNumberHelper {
    public static Rclub_Number_Settings__c settings;
    public static Date today;

    private static final String LANGUAGE_PREFERENCE_EN = 'EN';
    private static final String LANGUAGE_PREFERENCE_FR = 'FR';

    static {
        settings = Rclub_Number_Settings__c.getOrgDefaults();
        today = Date.today();
    }

    /**
    * This method used for generating single R-club number on one account.
    * @param account Account
    * @return String
    */
    public static String generateClcNumberSingleGeneral(Account account){
        String cardNumber = generateCardNumber(account);
        String cardNumberWithChecksum = cardNumber + Luhn.generateChecksum(cardNumber);

        ++settings.Number__c;
        update settings;

        return cardNumberWithChecksum;
    }

    /**
    * This method used for generating R-club numbers in account Account list.
    * @param newSObjects List<Account>
    * @return none.
    */
    public static void generateClcNumberGeneral(List<Account> newSObjects){
        generateClcNumber(newSObjects);

        update settings;
    }

    @TestVisible
    private static void generateClcNumber(List<Account> newSObjects){
        for (Account newAccount : newSObjects){
            if (newAccount.R_Club_Number__c == null || newAccount.R_Club_Number__c.isWhitespace()) {
                String cardNumber = generateCardNumber(newAccount);
                newAccount.R_Club_Number__c = cardNumber + Luhn.generateChecksum(cardNumber);
                newAccount.R_Club_Join_Date__c = today;
                ++settings.Number__c;
            }
        }
    }

    @TestVisible
    private static String generateCardNumber(Account newAccount){
        return String.valueOf(settings.IIN__c.round()) + generateCardType(newAccount) + String.valueOf(settings.Number__c.round()).leftPad(7, '0');
    }

    @TestVisible
    private static String generateCardType(Account newAccount){
        if (newAccount.Language_Preference__c == LANGUAGE_PREFERENCE_EN) {
            return String.valueOf(settings.Online_English__c.round());
        } else if (newAccount.Language_Preference__c == LANGUAGE_PREFERENCE_FR) {
            return String.valueOf(settings.Online_French__c.round());
        }

        return '0';
    }
}