force-app/main/default/objects/Account/fields/Loyalty_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loyalty Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loyalty_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In_Date__c</fullName>
    <label>Loyalty Opt In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_R_Club_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The main R-Club Number record associated with this account.</description>
    <inlineHelpText>The main R-Club Number record associated with this account.</inlineHelpText>
    <label>Primary R-Club Number</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>R_Club_Number__c.Account__r.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>R_Club_Number__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/R_Club_Join_Date__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Join_Date__c</fullName>
    <description>This signifies the date that a customer joined the R-Club rewards program.</description>
    <label>R-Club Join Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <description>Rewards number issued by Toys R Us.</description>
    <label>R-Club Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SFCC_update__c.field-meta.xml
<CustomField>
    <fullName>SFCC_update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SFCC update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/R_Club_Number__c.object-meta.xml
<CustomObject>
    <label>R Club Number</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>SFSC System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>R Club Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/R_Club_Number__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>R Club Numbers</relationshipLabel>
    <relationshipName>R_Club_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/Loyalty_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Loyalty Opt In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/Loyalty_Opt_In_Date__c.field-meta.xml
<CustomField>
    <fullName>Loyalty_Opt_In_Date__c</fullName>
    <label>Loyalty Opt In Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Join_Date__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Join_Date__c</fullName>
    <label>R Club Join Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <externalId>true</externalId>
    <label>R Club Number</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/RClubTriggerHandlerTest.cls
/**
 * Created by mike on 1/22/20.
 */

@isTest
private with sharing class RClubTriggerHandlerTest {

    @testSetup
    static void setup() {

        List<Account> testAccounts =  TRUTestDataFactory.createAccounts(1, 'EN');
        insert testAccounts;

    }


    /**
     * This method tests that 2 R-Club Numbers, inserted without Opt-in or Join Dates should result in the
     * latest inserted (highest ID) record becoming the primary value. The other Number should not be marked as
     * Primary.
     */
    @isTest
    private static void testInsertOfNewRClubNumbers_NoDates() {

        Account ac = [SELECT Id FROM Account LIMIT 1];

        R_Club_Number__c rc1 = new R_Club_Number__c(R_Club_Number__c = '11111', Account__c = ac.Id);
        R_Club_Number__c rc2 = new R_Club_Number__c(R_Club_Number__c = '22222', Account__c = ac.Id);

        List<R_Club_Number__c> rClubForInsert = new List<R_Club_Number__c>{rc1, rc2};

        Test.startTest();
        insert rClubForInsert;
        Test.stopTest();

        List<R_Club_Number__c> allRClubs = [SELECT Id, Primary__c FROM R_Club_Number__c];

        System.assertEquals(2, allRClubs.size());
        System.assertEquals(true, allRClubs.get(1).Primary__c);
        System.assertEquals(false, allRClubs.get(0).Primary__c);
    }

    /**
     * This method Tests a comparison of 2 records that have Loyalty Opt in and Join Dates set.
     * The record with the more recent date should win as primary.
     */
    @isTest
    private static void testInsertOfNewRClubNumbers_AllDates() {

        Account ac = [SELECT Id FROM Account LIMIT 1];

        R_Club_Number__c rc1 = new R_Club_Number__c(R_Club_Number__c = '11111', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2020'), R_Club_Join_Date__c = Date.parse('01/01/2020'));
        R_Club_Number__c rc2 = new R_Club_Number__c(R_Club_Number__c = '22222', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2019'), R_Club_Join_Date__c = Date.parse('01/01/2019'));
        R_Club_Number__c rc3 = new R_Club_Number__c(R_Club_Number__c = '33333', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2018'), R_Club_Join_Date__c = Date.parse('01/01/2018'));


        List<R_Club_Number__c> rClubForInsert = new List<R_Club_Number__c>{rc1, rc2, rc3};

        Test.startTest();
        insert rClubForInsert;
        Test.stopTest();

        List<R_Club_Number__c> allRClubs = [SELECT Id, Primary__c FROM R_Club_Number__c];

        System.assertEquals(3, allRClubs.size());
        System.assertEquals(true, allRClubs.get(0).Primary__c);
        System.assertEquals(false, allRClubs.get(1).Primary__c);
        System.assertEquals(false, allRClubs.get(2).Primary__c);
    }

    @isTest
    private static void testUpdateOfNewRClubNumbers_AllDates() {

        Account ac = [SELECT Id FROM Account LIMIT 1];

        R_Club_Number__c rc1 = new R_Club_Number__c(R_Club_Number__c = '11111', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2020'), R_Club_Join_Date__c = Date.parse('01/01/2020'));
        R_Club_Number__c rc2 = new R_Club_Number__c(R_Club_Number__c = '22222', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2019'), R_Club_Join_Date__c = Date.parse('01/01/2019'));
        R_Club_Number__c rc3 = new R_Club_Number__c(R_Club_Number__c = '33333', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2018'), R_Club_Join_Date__c = Date.parse('01/01/2018'));


        List<R_Club_Number__c> rClubForInsert = new List<R_Club_Number__c>{rc1, rc2, rc3};

        insert rClubForInsert;

        Test.startTest();
        rc2.Loyalty_Opt_In_Date__c = Date.parse('01/01/2021');
        RClubTriggerHandler.alreadyProcessedAccounts.clear(); // clear so we can recurse and re-execute the logic
        update rc2;
        Test.stopTest();

        List<R_Club_Number__c> allRClubs = [SELECT Id, Primary__c, R_Club_Number__c FROM R_Club_Number__c];

        System.assertEquals(3, allRClubs.size());
        System.assertEquals(false, allRClubs.get(0).Primary__c);
        System.assertEquals(true, allRClubs.get(1).Primary__c);
        System.assertEquals(false, allRClubs.get(2).Primary__c);
    }

    @isTest
    private static void testDeleteOfNewRClubNumbers_AllDates() {
        Account ac = [SELECT Id FROM Account LIMIT 1];

        R_Club_Number__c rc1 = new R_Club_Number__c(R_Club_Number__c = '11111', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2020'), R_Club_Join_Date__c = Date.parse('01/01/2020'));
        R_Club_Number__c rc2 = new R_Club_Number__c(R_Club_Number__c = '22222', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2019'), R_Club_Join_Date__c = Date.parse('01/01/2019'));
        R_Club_Number__c rc3 = new R_Club_Number__c(R_Club_Number__c = '33333', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2018'), R_Club_Join_Date__c = Date.parse('01/01/2018'));


        List<R_Club_Number__c> rClubForInsert = new List<R_Club_Number__c>{rc1, rc2, rc3};

        insert rClubForInsert;

        List<R_Club_Number__c> allRClubs = [SELECT Id, Primary__c, R_Club_Number__c FROM R_Club_Number__c];
        System.assertEquals(3, allRClubs.size());
        System.assertEquals(true, allRClubs.get(0).Primary__c);
        System.assertEquals(false, allRClubs.get(1).Primary__c);
        System.assertEquals(false, allRClubs.get(2).Primary__c);

        RClubTriggerHandler.alreadyProcessedAccounts.clear(); // clear so we can recurse and re-execute the logic
        delete rc1;

        allRClubs = [SELECT Id, Primary__c, R_Club_Number__c FROM R_Club_Number__c];
        System.assertEquals(2, allRClubs.size());
        System.assertEquals(true, allRClubs.get(0).Primary__c);
        System.assertEquals(false, allRClubs.get(1).Primary__c);
    }

    @isTest
    private static void testDeleteOfNewRClubNumbers_NODates() {
        Account ac = [SELECT Id FROM Account LIMIT 1];

        R_Club_Number__c rc1 = new R_Club_Number__c(R_Club_Number__c = '11111', Account__c = ac.Id);
        R_Club_Number__c rc2 = new R_Club_Number__c(R_Club_Number__c = '22222', Account__c = ac.Id);
        R_Club_Number__c rc3 = new R_Club_Number__c(R_Club_Number__c = '33333', Account__c = ac.Id);


        List<R_Club_Number__c> rClubForInsert = new List<R_Club_Number__c>{rc1, rc2, rc3};

        insert rClubForInsert;

        List<R_Club_Number__c> allRClubs = [SELECT Id, Primary__c, R_Club_Number__c FROM R_Club_Number__c];
        System.assertEquals(3, allRClubs.size());
        System.assertEquals(false, allRClubs.get(0).Primary__c);
        System.assertEquals(false, allRClubs.get(1).Primary__c);
        System.assertEquals(true, allRClubs.get(2).Primary__c);

    }

    @isTest
    private static void testRollups() {
        Account ac = [SELECT Id FROM Account LIMIT 1];

        R_Club_Number__c rc1 = new R_Club_Number__c(R_Club_Number__c = '11111', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2020'), R_Club_Join_Date__c = Date.parse('01/01/2020'));
        R_Club_Number__c rc2 = new R_Club_Number__c(R_Club_Number__c = '22222', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2019'), R_Club_Join_Date__c = Date.parse('01/01/2019'));
        R_Club_Number__c rc3 = new R_Club_Number__c(R_Club_Number__c = '33333', Account__c = ac.Id, Loyalty_Opt_In_Date__c = Date.parse('01/01/2018'), R_Club_Join_Date__c = Date.parse('01/01/2018'));


        List<R_Club_Number__c> rClubForInsert = new List<R_Club_Number__c>{rc1, rc2, rc3};

        insert rClubForInsert;

        ac = [SELECT Id, Loyalty_Opt_In__c, Loyalty_Opt_In_Date__c, R_Club_Number__c, R_Club_Join_Date__c, Primary_R_Club_Number__c, SFCC_update__c FROM Account];

        System.assertEquals(false, ac.Loyalty_Opt_In__c);
        System.assertEquals(Date.parse('01/01/2020'), ac.Loyalty_Opt_In_Date__c);
        System.assertEquals(Date.parse('01/01/2020'), ac.R_Club_Join_Date__c);
        System.assertEquals('11111', ac.R_Club_Number__c);
        // make sure the SFCC_update__c flag is reset back to false after update
        //System.assertEquals(false, ac.SFCC_update__c);
    }

}