force-app/main/default/objects/Account/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <description>Rewards number issued by Toys R Us.</description>
    <label>R-Club Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Child Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Children</relationshipLabel>
    <relationshipName>Children</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Child__c/fields/Birthday__c.field-meta.xml
<CustomField>
    <fullName>Birthday__c</fullName>
    <label>Birthday</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Child__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/R_Club_Number__c.object-meta.xml
<CustomObject>
    <label>R Club Number</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>SFSC System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>R Club Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/R_Club_Number__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>R Club Numbers</relationshipLabel>
    <relationshipName>R_Club_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <externalId>true</externalId>
    <label>R Club Number</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Registry__c/Registry__c.object-meta.xml
<CustomObject>
    <label>Registry</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Registry System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registry__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Registries</relationshipLabel>
    <relationshipName>Registries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountMergeBatchJobTest.cls
@isTest
private class AccountMergeBatchJobTest {
    @testSetup
    static void setup() {
        List<Account> accounts = new List<Account>();
        List<Case> cases = new List<Case>();
        List<Child__c> children = new List<Child__c>();
        List<Registry__c> registries = new List<Registry__c>();
        List<R_Club_Number__c> rClubNumbers = new List<R_Club_Number__c>();

        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();

        for (Integer i=0;i<50;i++) {
            accounts.add(new Account(
                    LastName='Account '+i,
                    PersonEmail = 'testemail@test.mail',
                    RecordTypeId = rtId
            ));
        }

        insert accounts;

        for (Integer i=0;i<50;i++) {
            cases.add(new Case(Subject = 'test', AccountId = accounts.get(i).Id, ContactId = accounts.get(i).PersonContactId));
        }

        insert cases;

        for (Integer i=0;i<50;i++) {
            children.add(new Child__c(Account__c = accounts.get(i).Id, Name__c = 'test-child-'+i, Birthday__c = Date.today()));
        }

        insert children;
    }

    @IsTest
    static void test() {
        Test.startTest();
        AccountMergeBatchJob2 uca = new AccountMergeBatchJob2();
        Id batchId = Database.executeBatch(uca, 50);
        Test.stopTest();

        System.assertEquals(1, [select count() from Account where PersonEmail = 'testemail@test.mail']);
        System.assertEquals(50, [SELECT Id, (Select Id FROM Cases) FROM Account WHERE PersonEmail = 'testemail@test.mail'].Cases.size());
        System.assertEquals(50, [SELECT Id, (Select Id FROM Children__r) FROM Account WHERE PersonEmail = 'testemail@test.mail'].Children__r.size());
    }
}