force-app/main/default/objects/Account/fields/R_Club_Join_Date__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Join_Date__c</fullName>
    <description>This signifies the date that a customer joined the R-Club rewards program.</description>
    <label>R-Club Join Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <description>Rewards number issued by Toys R Us.</description>
    <label>R-Club Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/R_Club_Number__c.object-meta.xml
<CustomObject>
    <label>R Club Number</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>SFSC System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>R Club Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/R_Club_Number__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>R Club Numbers</relationshipLabel>
    <relationshipName>R_Club_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Join_Date__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Join_Date__c</fullName>
    <label>R Club Join Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <externalId>true</externalId>
    <label>R Club Number</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchForAccountQueries1.cls
global class BatchForAccountQueries1 implements Database.Batchable<sObject>,Database.Stateful {
    
    public integer countCase1 = 0;
    public integer countCase3 = 0;
    public List<Account> accountListCase1 = new List<Account>();
    public List<String> accountListCase3 = new List<String>();


    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query =  ' SELECT Id, R_Club_Number__c ';
               query += ' FROM Account WHERE R_Club_Number__c != NULL';

        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<Account> accountList) {
        //List<Account> toUpdateAccountList = new List<Account>();
        List<Account> toUpdateAccountList =  [SELECT Id, PersonEmail, R_Club_Number__c, R_Club_Join_Date__c,
                                              (SELECT R_Club_Number__c FROM R_Club_Numbers__r WHERE Primary__c = true LIMIT 1)
                                              FROM Account WHERE R_Club_Number__c != NULL AND id IN: accountList];
        
        for(Account accountRecord : toUpdateAccountList){
            /* if(accountRecord.R_Club_Numbers__r.size() == 0){
                accountListCase3.add(accountRecord.Id);
                countCase3++;
            }*/
            for(R_Club_Number__c rClubeNumberRec : accountRecord.R_Club_Numbers__r){
                if(accountRecord.R_Club_Number__c != rClubeNumberRec.R_Club_Number__c ){
                    accountListCase1.add(accountRecord);
                    countCase1++;
                }
            }
         }
    }   
    
    global void finish(Database.BatchableContext BC) {
        //Send an email to the User after your batch completes
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'nikita@dreamwares.com', 'annemarie@majente.com'};
            mail.setToAddresses(toAddresses);
        mail.setSubject('Batch Apex Job is done for Rlub object exists for the account and the account RClub number does not = Primary Rclub number ');
        mail.setPlainTextBody(' Count '+ countCase1+'  Total AccountList  ' +'  '+ JSON.serialize(accountListCase1));
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}