force-app/main/default/objects/Account/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <description>Rewards number issued by Toys R Us.</description>
    <label>R-Club Number</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/R_Club_Number__c.object-meta.xml
<CustomObject>
    <label>R Club Number</label>
    <nameField>
        <displayFormat>R{000000}</displayFormat>
        <label>SFSC System Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>R Club Numbers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/R_Club_Number__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>R Club Numbers</relationshipLabel>
    <relationshipName>R_Club_Numbers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/R_Club_Number__c/fields/R_Club_Number__c.field-meta.xml
<CustomField>
    <fullName>R_Club_Number__c</fullName>
    <externalId>true</externalId>
    <label>R Club Number</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/BatchForAccountQueries4.cls
global class BatchForAccountQueries4 implements Database.Batchable<sObject>,Database.Stateful {
    
    public integer count = 0;
    public List<String> accountListCase3 = new List<String>();

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query =  ' SELECT Id, R_Club_Number__c ';
               query += ' FROM Account WHERE R_Club_Number__c != NULL';

        return Database.getQueryLocator(query);
    }
   
    global void execute(Database.BatchableContext BC, List<Account> accountList) {
       
       // Map<String, List<R_Club_Number__c>> accountIdRClubMap = new Map<String, R_Club_Number__c>();
        
       /* List<R_Club_Number__c> RClubList = [SELECT Id, R_Club_Number__c, Account__c 
                                            FROM R_Club_Number__c 
                                            WHERE Account__c IN: accountList];
        for(R_Club_Number__c RClubRec : RClubList){
            accountIdRClubMap.put(RClubRec.Account__c, RClubRec);
        }*/
        
        List<Account> accountNewList = [SELECT Id, R_Club_Number__c, (SELECT Id, R_Club_Number__c, Account__c FROM R_Club_Numbers__r  WHERE Primary__c 
                                                                      != true)
                                        FROM Account
                                        WHERE Id IN: accountList];
        
        for(Account accountRecord : accountNewList){
            if(accountRecord.R_Club_Numbers__r.size() == 1){
                if(accountRecord.R_Club_Numbers__r[0].R_Club_Number__c == accountRecord.R_Club_Number__c){
                    accountListCase3.add(accountRecord.Id);
                    count++;
                }
            }
         }
    }   
    
    global void finish(Database.BatchableContext BC) {
        system.debug(count);
        //Send an email to the User after your batch completes
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'nikita@dreamwares.com', 'annemarie@majente.com' };
            mail.setToAddresses(toAddresses);
        mail.setSubject('Batch Apex Job is done for RClub number on the account is not null and one RClub exists for the account with same RClube on that account');
        mail.setPlainTextBody(' Count '+ count + '  Total AccountIds == ' +'  '+ JSON.serialize(accountListCase3));
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}