force-app/main/default/objects/Child__c/Child__c.object-meta.xml
<CustomObject>
    <label>Child</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Child Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Children</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Child__c/fields/Duplicate_Record__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Duplicate Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChildDeletionBatch.cls
public class ChildDeletionBatch implements Database.Batchable<Sobject>{
	public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'Select id from child__c where duplicate_record__c = true '; 
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Sobject> scope){
        delete scope; 
    }
    
    public void finish(Database.BatchableContext BC){ 
    }
}